//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD4e.CombatManager.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnD4e.CombatManager.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.bindingHandlers.abilityScore = {
        ///    update: function (element, valueAccessor) {
        ///        var value = valueAccessor(),
        ///            bonus = Math.floor(value / 2) - 5,
        ///            sign = bonus &gt; 0 ? &apos;+&apos; : &apos;&apos;,
        ///            text = value + &apos; (&apos; + sign + bonus + &apos;)&apos;;
        ///        ko.bindingHandlers.text.update(element, function() { return text; });
        ///    }
        ///};
        ///
        ///ko.bindingHandlers.stringArray = {
        ///    update: function (element, valueAccessor, allBindingsAccessor) {
        ///        var list = ko.utils.unwrapObservable( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bindingHandlers_js {
            get {
                return ResourceManager.GetString("bindingHandlers_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Knockout JavaScript library v3.0.0
        ///// (c) Steven Sanderson - http://knockoutjs.com/
        ///// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///
        ///(function(){
        ///var DEBUG=true;
        ///(function(undefined){
        ///    // (0, eval)(&apos;this&apos;) is a robust way of getting a reference to the global object
        ///    // For details, see http://stackoverflow.com/questions/14119988/return-this-0-evalthis/14120023#14120023
        ///    var window = this || (0, eval)(&apos;this&apos;),
        ///        document = window[&apos;document&apos;],
        ///        navigator = window[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout_3_0_0_debug_js {
            get {
                return ResourceManager.GetString("knockout_3_0_0_debug_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* --- String interpolating binding provider ---
        ///   Allows {{ expr }} syntax in DOM. Could be an official KO plugin
        ///   loaded from a separate file. Note that preprocessNode is a fairly
        ///   low-level API that developers are not often expected to use directly.
        ///*/
        ///
        ///var StringInterpolatingBindingProvider = function() {
        ///    this.constructor = StringInterpolatingBindingProvider;
        ///
        ///    var expressionRegex = /{{([\s\S]+?)}}/g;
        ///
        ///    this.preprocessNode = function(node) {
        ///        if (node.nodeType === 3 &amp;&amp; node.nodeVal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout_StringInterpolatingBindingProvider_js {
            get {
                return ResourceManager.GetString("knockout_StringInterpolatingBindingProvider_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Modernizr v2.6.2
        /// * www.modernizr.com
        /// *
        /// * Copyright (c) Faruk Ates, Paul Irish, Alex Sexton
        /// * Available under the BSD and MIT licenses: www.modernizr.com/license/
        /// */
        ///
        ////*
        /// * Modernizr tests which native CSS3 and HTML5 features are available in
        /// * the current UA and makes the results available to you in two ways:
        /// * as properties on a global Modernizr object, and as classes on the
        /// * &lt;html&gt; element. This information allows you to progressively enhance
        /// * your pages with a granular level of control  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modernizr_2_6_2_js {
            get {
                return ResourceManager.GetString("modernizr_2_6_2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title data-bind=&quot;text: Monster().Name&quot;&gt;&lt;/title&gt;
        ///    &lt;meta name=&quot;description&quot; content=&quot;D&amp;amp;D 4E Stat Block display&quot; /&gt;
        ///    &lt;meta name=&quot;author&quot; content=&quot;Jason Fischer&quot; /&gt;
        ///    &lt;script type=&apos;text/javascript&apos; src=&apos;underscore.js&apos;&gt;&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos; src=&apos;http://cdnjs.cloudflare.com/ajax/libs/jquery/1.10.2/jquery.js&apos;&gt;&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos; src=&apos;knockout-2.2.1.debug.js&apos;&gt;&lt;/script&gt;
        ///    &lt;script type=&apos;text/javascript&apos; src=&apos;bind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsterStatblock_html {
            get {
                return ResourceManager.GetString("monsterStatblock_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //var debugJson = &apos;{&quot;CompendiumUrl&quot;:&quot;http://www.wizards.com/dndinsider/compendium/monster.aspx?id=4578&quot;,&quot;Description&quot;:&quot;&quot;,&quot;GroupRole&quot;:&quot;Standard&quot;,&quot;IsLeader&quot;:false,&quot;Keywords&quot;:[],&quot;Immunities&quot;:[],&quot;Origin&quot;:&quot;Immortal&quot;,&quot;Phasing&quot;:false,&quot;Regeneration&quot;:0,&quot;Resistances&quot;:[],&quot;Role&quot;:&quot;Soldier&quot;,&quot;SavingThrows&quot;:0,&quot;SourceBook&quot;:&quot;Plane Above&quot;,&quot;SourceBooks&quot;:null,&quot;Tactics&quot;:null,&quot;Type&quot;:&quot;Humanoid&quot;,&quot;Weaknesses&quot;:[{&quot;Name&quot;:&quot;Acid&quot;,&quot;Details&quot;:&quot;or fire (if the battlesworn war troll defender takes acid or fire damage&quot;,&quot;Value&quot;:0},{&quot;Name&quot;:&quot;its&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string monsterStatblock_js {
            get {
                return ResourceManager.GetString("monsterStatblock_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v2.1.2 | MIT License | git.io/normalize */
        ///
        ////* ==========================================================================
        ///   HTML5 display definitions
        ///   ========================================================================== */
        ///
        ////**
        /// * Correct `block` display not defined in IE 8/9.
        /// */
        ///
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///nav,
        ///section,
        ///summary {
        ///    display: block;
        ///}
        ///
        ////**
        /// * Correct `inline-block` display not defined in IE 8/9.
        /// */
        ///
        ///audio,
        ///canvas, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string normalize_css {
            get {
                return ResourceManager.GetString("normalize_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {font-family: Arial, Sans-Serif; font-size: 9.5pt}  
        ///body {margin: 0px; padding: 0px; text-align:left; font-weight: normal;}
        ///table {border: 0px; cellpadding: 0px; cellspacing: 0px;}
        ///DIV.symbol {font-family: 4etools symbols} 
        ///DIV.mbheadleft {float: left;  align: left; color: #ffffff; font-size: 13px; font-weight: bold;}  
        ///DIV.mbheadright {float: right; align: right; color: #ffffff; font-size: 13px; font-weight: bold;}  
        ///DIV.mbsubleft {float: left; align: left; color: #ffffff;}  
        ///DIV.mbsubright {f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statblock_css {
            get {
                return ResourceManager.GetString("statblock_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     Underscore.js 1.5.2
        /////     http://underscorejs.org
        /////     (c) 2009-2013 Jeremy Ashkenas, DocumentCloud and Investigative Reporters &amp; Editors
        /////     Underscore may be freely distributed under the MIT license.
        ///
        ///(function() {
        ///
        ///  // Baseline setup
        ///  // --------------
        ///
        ///  // Establish the root object, `window` in the browser, or `exports` on the server.
        ///  var root = this;
        ///
        ///  // Save the previous value of the `_` variable.
        ///  var previousUnderscore = root._;
        ///
        ///  // Establish the object that ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string underscore_js {
            get {
                return ResourceManager.GetString("underscore_js", resourceCulture);
            }
        }
    }
}
