//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DnD4e.CombatManager.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DnD4e.CombatManager.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.10.2
        /// * http://jquery.com/
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// *
        /// * Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors
        /// * Released under the MIT license
        /// * http://jquery.org/license
        /// *
        /// * Date: 2013-07-03T13:48Z
        /// */
        ///(function( window, undefined ) {
        ///
        ///// Can&apos;t do this because several apps including ASP.NET trace
        ///// the stack via arguments.caller.callee and Firefox dies if
        ///// you try to trace through &quot;use strict&quot; call chains. (#13335)
        ///// Suppor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_10_2_js {
            get {
                return ResourceManager.GetString("jquery_1_10_2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///    json2.js
        ///    2013-05-26
        ///
        ///    Public Domain.
        ///
        ///    NO WARRANTY EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.
        ///
        ///    See http://www.JSON.org/js.html
        ///
        ///
        ///    This code should be minified before deployment.
        ///    See http://javascript.crockford.com/jsmin.html
        ///
        ///    USE YOUR OWN COPY. IT IS EXTREMELY UNWISE TO LOAD CODE FROM SERVERS YOU DO
        ///    NOT CONTROL.
        ///
        ///
        ///    This file creates a global JSON object containing two methods: stringify
        ///    and parse.
        ///
        ///        JSON.stringify(value, replacer, space [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json2_js {
            get {
                return ResourceManager.GetString("json2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Knockout JavaScript library v2.2.1
        ///// (c) Steven Sanderson - http://knockoutjs.com/
        ///// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///
        ///(function(){
        ///var DEBUG=true;
        ///(function(window,document,navigator,jQuery,undefined){
        ///!function(factory) {
        ///    // Support three module loading scenarios
        ///    if (typeof require === &apos;function&apos; &amp;&amp; typeof exports === &apos;object&apos; &amp;&amp; typeof module === &apos;object&apos;) {
        ///        // [1] CommonJS/Node.js
        ///        var target = module[&apos;exports&apos;] || exports; // module.exports i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout_2_2_1_debug_js {
            get {
                return ResourceManager.GetString("knockout_2_2_1_debug_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// Knockout Mapping plugin v2.4.0
        ////// (c) 2013 Steven Sanderson, Roy Jacobs - http://knockoutjs.com/
        ////// License: MIT (http://www.opensource.org/licenses/mit-license.php)
        ///(function (factory) {
        ///	// Module systems magic dance.
        ///
        ///	if (typeof require === &quot;function&quot; &amp;&amp; typeof exports === &quot;object&quot; &amp;&amp; typeof module === &quot;object&quot;) {
        ///		// CommonJS or Node: hard-coded dependency on &quot;knockout&quot;
        ///		factory(require(&quot;knockout&quot;), exports);
        ///	} else if (typeof define === &quot;function&quot; &amp;&amp; define[&quot;amd&quot;]) {
        ///		// AMD anonymous [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string knockout_mapping_latest_debug_js {
            get {
                return ResourceManager.GetString("knockout_mapping_latest_debug_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Modernizr v2.6.2
        /// * www.modernizr.com
        /// *
        /// * Copyright (c) Faruk Ates, Paul Irish, Alex Sexton
        /// * Available under the BSD and MIT licenses: www.modernizr.com/license/
        /// */
        ///
        ////*
        /// * Modernizr tests which native CSS3 and HTML5 features are available in
        /// * the current UA and makes the results available to you in two ways:
        /// * as properties on a global Modernizr object, and as classes on the
        /// * &lt;html&gt; element. This information allows you to progressively enhance
        /// * your pages with a granular level of control  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string modernizr_2_6_2_js {
            get {
                return ResourceManager.GetString("modernizr_2_6_2_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! normalize.css v2.1.2 | MIT License | git.io/normalize */
        ///
        ////* ==========================================================================
        ///   HTML5 display definitions
        ///   ========================================================================== */
        ///
        ////**
        /// * Correct `block` display not defined in IE 8/9.
        /// */
        ///
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///nav,
        ///section,
        ///summary {
        ///    display: block;
        ///}
        ///
        ////**
        /// * Correct `inline-block` display not defined in IE 8/9.
        /// */
        ///
        ///audio,
        ///canvas, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string normalize_css {
            get {
                return ResourceManager.GetString("normalize_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html {font-family: Arial, Sans-Serif; font-size: 9.5pt}  
        ///body {margin: 0px; padding: 0px; text-align:left; font-weight: normal;}
        ///table {border: 0px; cellpadding: 0px; cellspacing: 0px;}
        ///DIV.symbol {font-family: 4etools symbols} 
        ///DIV.mbheadleft {float: left;  align: left; color: #ffffff; font-size: 13px; font-weight: bold;}  
        ///DIV.mbheadright {float: right; align: right; color: #ffffff; font-size: 13px; font-weight: bold;}  
        ///DIV.mbsubleft {float: left; align: left; color: #ffffff;}  
        ///DIV.mbsubright {f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statblock_css {
            get {
                return ResourceManager.GetString("statblock_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;CombatManager&lt;/title&gt;
        ///        &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///        &lt;meta name=&quot;description&quot; content=&quot;D&amp;amp;D 4E Stat Block display&quot; /&gt;
        ///        &lt;meta name=&quot;author&quot; content=&quot;Jason Fischer&quot; /&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///        &lt;div class=&quot;ggdark&quot;&gt;
        ///            &lt;div class=&quot;mbheadleft&quot;&gt;&lt;span data-bind=&quot;text: Name()&quot;&gt;Ghost Beholder&lt;/span&gt;&lt;/div&gt;
        ///            &lt;div class=&quot;mbheadright&quot;&gt;&lt;span data-bind=&quot;text: L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statblockMonster_html {
            get {
                return ResourceManager.GetString("statblockMonster_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //var text = &apos;{&quot;Type&quot;:&quot;Monster&quot;,&quot;Monster&quot;:{&quot;AbilityScores&quot;:{&quot;Strength&quot;:12,&quot;Constitution&quot;:19,&quot;Dexterity&quot;:25,&quot;Intelligence&quot;:22,&quot;Wisdom&quot;:16,&quot;Charisma&quot;:25},&quot;ActionPoints&quot;:1,&quot;Alignment&quot;:&quot;Evil&quot;,&quot;CompendiumUrl&quot;:&quot;http://www.wizards.com/dndinsider/compendium/monster.aspx?id=4808&quot;,&quot;Defenses&quot;:{&quot;AC&quot;:30,&quot;Fortitude&quot;:29,&quot;Reflex&quot;:30,&quot;Will&quot;:30},&quot;Description&quot;:&quot;Death need not be an end to avarice and ambition. As living creatures, beholders must eventually fall from the air to rot on the hated earth. Yet some have the willpow [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string statblockMonster_js {
            get {
                return ResourceManager.GetString("statblockMonster_js", resourceCulture);
            }
        }
    }
}
